spring.application.name=whister-agendamentos-api

spring.datasource.url=jdbc:postgresql://localhost:5432/whister-agendamentos-db
spring.datasource.username=postgres
spring.datasource.password=622677

# Configurações do Hibernate e JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true